name: DVNAPOC

on:
 workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Pull DVNA Image
        run: docker pull appsecco/dvna     
      - name: Run Docker DVNA
        run: docker run --name dvna -p 5050:5050 -d appsecco/dvna:sqlite
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
         target: "http://testphp.vulnweb.com/"
